
# This workflow is triggered on pushes to the main branch.
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      # This step assumes you have Firebase CLI installed and configured.
      # It uses secrets for Firebase service account and project ID for secure deployment.
      # Ensure FIREBASE_SERVICE_ACCOUNT and FIREBASE_PROJECT_ID are set in your repo's secrets.
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}' # Automatically provided by GitHub Actions
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' # Your Firebase service account JSON
          projectId: '${{ secrets.FIREBASE_PROJECT_ID }}' # Your Firebase project ID
          channelId: live # Deploy to the live channel
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks # Enable Next.js support in Firebase CLI
          # Pass Next.js build environment variables if needed, ensure they are also in GitHub secrets
          # Example: NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          # It's generally better if these are baked into the build via process.env from next.config.ts
          # and only secrets sensitive to the deployment step are here.
